In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
df

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
len(df)

150

In [6]:
df2 = df.sample(n=110)
df2

     sepallength  sepalwidth  petallength  petalwidth            class
64           5.6         2.9          3.6         1.3  Iris-versicolor
123          6.3         2.7          4.9         1.8   Iris-virginica
135          7.7         3.0          6.1         2.3   Iris-virginica
16           5.4         3.9          1.3         0.4      Iris-setosa
40           5.0         3.5          1.3         0.3      Iris-setosa
..           ...         ...          ...         ...              ...
55           5.7         2.8          4.5         1.3  Iris-versicolor
45           4.8         3.0          1.4         0.3      Iris-setosa
142          5.8         2.7          5.1         1.9   Iris-virginica
105          7.6         3.0          6.6         2.1   Iris-virginica
12           4.8         3.0          1.4         0.1      Iris-setosa

[110 rows x 5 columns]

In [7]:
df2.reset_index(inplace=True, drop=True)

In [8]:
df2

     sepallength  sepalwidth  petallength  petalwidth            class
0            5.6         2.9          3.6         1.3  Iris-versicolor
1            6.3         2.7          4.9         1.8   Iris-virginica
2            7.7         3.0          6.1         2.3   Iris-virginica
3            5.4         3.9          1.3         0.4      Iris-setosa
4            5.0         3.5          1.3         0.3      Iris-setosa
..           ...         ...          ...         ...              ...
105          5.7         2.8          4.5         1.3  Iris-versicolor
106          4.8         3.0          1.4         0.3      Iris-setosa
107          5.8         2.7          5.1         1.9   Iris-virginica
108          7.6         3.0          6.6         2.1   Iris-virginica
109          4.8         3.0          1.4         0.1      Iris-setosa

[110 rows x 5 columns]

In [10]:
df2.to_csv("iris_data.csv", index=False)